web:
  image: php:7.0-apache
  links:
    - database
  volumes:
    - .:/var/www/html

database:
  image: mysql:5.5
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: default
